#!/data/data/com.termux/files/usr/bin/bash
# HUD Panel: ryujin_status.sh — Auto-generated by RYUJIN v4.0
# Shows AI engine status in main RDxOS HUD

LR='\033[1;31m'; LG='\033[1;32m'; Y='\033[1;33m'
C='\033[0;36m'; P='\033[1;35m'; GR='\033[1;30m'
BL='\033[5m'; NC='\033[0m'

SOUL_DIR="$HOME/.ryujin"
SOUL_CONFIG="$SOUL_DIR/soul.conf"
[ -f "$SOUL_CONFIG" ] && source "$SOUL_CONFIG" 2>/dev/null

if pgrep -x "ollama" >/dev/null 2>&1; then
    ACTIVE=$(ollama ps 2>/dev/null | awk 'NR>1 {print $1}' | head -1)
    if [ -n "$ACTIVE" ]; then
        echo -e " ${GR}◉ RYUJIN${NC}  ${LG}${BL}●${NC} ${LG}LIVE${NC}  ${GR}│${NC}  ${P}${ACTIVE}${NC}  ${GR}│${NC}  ${C}NEURAL LINK${NC}"
    else
        echo -e " ${GR}◉ RYUJIN${NC}  ${LG}●${NC} ${LG}SERVER ON${NC}  ${GR}│${NC}  ${Y}${SOUL_NAME:-ryujin}${NC}  ${GR}│${NC}  ${GR}idle${NC}"
    fi
else
    echo -e " ${GR}◉ RYUJIN${NC}  ${LR}○${NC} ${GR}offline${NC}  ${GR}│${NC}  ${GR}use RYUJIN.sh to start${NC}"
fi
